repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
  # - repo: https://github.com/pre-commit/mirrors-prettier
  #   rev: "v4.0.0-alpha.8" # Use the sha or tag you want to point at
  #   hooks:
  #     - id: prettier
  - repo: https://github.com/Lucas-C/pre-commit-hooks-java
    rev: 1.3.10
    hooks:
      - id: validate-html
  - repo: https://gitlab.com/devopshq/gitlab-ci-linter
    rev: v1.0.6
    hooks:
      - id: gitlab-ci-linter
